services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db_test:
        condition: service_healthy
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    command: ./main_test

  db_test:
    image: postgres
    hostname: ${POSTGRES_TEST_NAME}
    environment: 
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db: