services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "${APP_PORT}:${APP_PORT}"

  db:
    image: postgres
    hostname: ${POSTGRES_DEV_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
